### PR TITLE
Test multiple PARI versions

### PR DESCRIPTION
**Pull request by jdemeyer**
We should test:
- PARI 2.8.1 (the oldest version supported)
- PARI 2.9.3 (latest stable)
- PARI master

### CODE REVIEW

**Comment by jdemeyer** [comment]
@videlec Please review, it would be good to include this too in the next cypari2 release.

**Comment by videlec** [comment]
What is the `2.8.beta` version that is tested at https://travis-ci.org/defeo/cypari2/builds/266930844?

It would be better to do `bash -x .travis-install-pari.sh` to actually see the executed commands.

**Comment by videlec** [comment]
travis is supporting caching: https://docs.travis-ci.com/user/caching/. Using it would significantly speed up pari download and compilation. Though I am not sure if a different cache is automatically used for each environment.

**Comment by jdemeyer** [comment]
> What is the 2.8.beta version that is tested at https://travis-ci.org/defeo/cypari2/builds/266930844

Ask upstream, seriously. They have a strange version numbering scheme.

**Comment by jdemeyer** [comment]
> Using it would significantly speed up pari download and compilation

For compilation, we could use ccache indeed.

For downloads, Travis CI documents that this is not the intended use of caching: https://docs.travis-ci.com/user/caching/#Things-not-to-cache

**Comment by jdemeyer** [comment]
I tried to setup ccache, but I'm not entirely sure that it works. In any case, this shouldn't prevent this PR from being merged.

**Comment by videlec** [comment]
It should work, though we won't notice a difference on the first build...

**Comment by videlec** [comment]
It would be cleaner to have two environment variables `PARI_VERSION` `PARI_URL` instead of a if/else statement and a for loop in the script.

**Comment by jdemeyer** [comment]
> It would be cleaner to have two environment variables PARI_VERSION PARI_URL instead of a if/else statement and a for loop in the script.

I don't know how you would do that, but feel free to implement it.

**Comment by jdemeyer** [comment]
Caching seems to work now.

**Comment by videlec** [comment]
One good thing would actually be to activate ccache for PARI compilation but disable it for cypari2. These are big useless C and .so files that you do not want to keep.

**Comment by jdemeyer** [comment]
> These are big useless C and .so files that you do not want to keep.

Why that? ccache can also speed up compilations of Cython-generated C files.

**Comment by videlec** [comment]
I tried a simpler script version on the branch test_pari_versions-bis

**Comment by videlec** [comment]
> These are big useless C and .so files that you do not want to keep.

>> Why that? ccache can also speed up compilations of Cython-generated C files.

I was worried about the cache limit being set to 256M. With a quick `du -sh`

  - PARI is 187M
  - cypari2 is 41M

**Comment by videlec** [comment]
In Travis, do you know why does `$ pip install --verbose -r requirements.txt` takes so long (~3 min)?

**Comment by jdemeyer** [comment]
> In Travis, do you know why does $ pip install --verbose -r requirements.txt takes so long (~3 min)?

Cython takes a while to compile because it uses itself to compile itself to C. And cysignals also uses Cython, so it also needs to be compiled. But `ccache` should help here...

**Comment by jdemeyer** [comment]
> I tried a simpler script version on the branch test_pari_versions-bis

See #32

**Comment by jdemeyer** [comment]
> I was worried about the cache limit being set to 256M.

First of all, the limit can be changed. Second, it seems that the cache is only a bit over 100MB, so 256MB should be large enough.

**Comment by videlec** [comment]
If Cython needs to be compiled then 256M is definitely a too low limit for ccache.

**Comment by jdemeyer** [comment]
> If Cython needs to be compiled then 256M is definitely a too low limit for ccache.

Why do you think so? Look at the build logs, you see something like
```
cache directory                     /home/travis/.ccache

cache hit (direct)                     0

cache hit (preprocessed)               0

cache miss                           170

called for link                       55

called for preprocessing               8

bad compiler arguments                 1

autoconf compile/link                  8

no input file                          5

files in cache                       205

cache size                         125.3 Mbytes

max cache size                     256.0 Mbytes
```

**Comment by jdemeyer** [comment]
I just realized that caching might not work properly with `pip install` because it uses a random temporary directory which changes every time. I'll try to fix this

See also https://ccache.samba.org/manual.html#_compiling_in_different_directories

**Comment by videlec** [comment]
> I just realized that caching might not work properly with pip install because it uses a random temporary directory which changes every time. I'll try to fix this

Don't the `--build` option of `pip` would settle that problem?
```
-b, --build <dir>           Directory to unpack packages into and build in.
```

**Comment by videlec** [comment]
(not sure https://github.com/pypa/pip/issues/4262)

**Comment by videlec** [comment]
But travis does support pip cachig (https://docs.travis-ci.com/user/caching/)
```
language: python

cache: pip
```

**Comment by jdemeyer** [comment]
> Don't the --build option of pip would settle that problem?

In theory, yes. In practice, it doesn't actually seem to work: https://github.com/pypa/pip/issues/4242

**Comment by jdemeyer** [comment]
Hmm, the actual issue might be https://github.com/pypa/pip/issues/804

**Pull request merged**
