### PR TITLE
Functions of pari

### LINKED ISSUE #8: methods vs functions
Currently and mostly for historical reasons, cypari2 works with methods instead of functions. For example `pari(2).zeta()` instead of `pari.zeta(2)`. It makes a big difference with the GP language that might be some trouble for PARI users. It should not be hard to implement a functional version using script for automatic generation.

The user interface might be something like

    >>> from cypari2.functions import *
    >>> zeta(2)
    1.64493406684823

### PR DESCRIPTION
**Pull request by jdemeyer**
Fix #8:
```
sage: from cypari2 import Pari
sage: pari = Pari()
sage: pari.zeta(2)
1.64493406684823
```

### CODE REVIEW

**Comment by jdemeyer** [comment]
@videlec @defeo Needs review...

**Comment by videlec** [comment]
There is an issue with the docstrings generated in `auto_instance.pxi`: linebreaks are not linebreaks but `\\n`

    def Polrev(self, t, v=None):
        r'''
        b'Transform the object :math:`t` into a polynomial\n        with main variable :math:`v`. If :math:`t` is a scalar, this gives a constant polynomial.\n        If :math:`t` is a power series, the effect is identical to :literal:`truncate`, i.e.\xc2\xa0it\n        chops off the :math:`O(X^k)`.\n        \n        The main use of this function is when :math:`t` is a vector: it creates the\n        polynomial whose coefficients are given by :math:`t`, with :math:`t[1]` being the\n        constant term. :literal:`Pol` can be used if one wants :math:`t[1]` to be the leading\n        coefficient:\n        \n        ::\n        \n            ? Polrev([1,2,3])\n            %1 = 3*x^2 + 2*x + 1\n            ? Pol([1,2,3])\n            %2 = x^2 + 2*x + 3\n        \n        The reciprocal function of :literal:`Pol` (resp.\xc2\xa0:literal:`Polrev`) is :literal:`Vec` (resp.\xc2\xa0\n        :literal:`Vecrev`).'
        '''

**Comment by videlec** [comment]
This is actually the same in `auto_gen.pxi`.

**Comment by jdemeyer** [comment]
That looks like a Python 3 issue (`bytes` vs `unicode`) which is unrelated to this pull request.

**Comment by jdemeyer** [comment]
I will look into that.

**Comment by jdemeyer** [comment]
> There is an issue with the docstrings generated in auto_instance.pxi: linebreaks are not linebreaks but \\n

This is now #25.

**Comment by videlec** [comment]
It is ok for me.

**Pull request merged**
