### PR TITLE
Add a tip for installation in README (cysignal dependance)

### PR DESCRIPTION
**Pull request by vinklein**

### CODE REVIEW

**Comment by jdemeyer** [comment]
requirement -> requirements

And why not re-install `cypari2` with `--upgrade`? It seems to me that the error could come from any package linking against PARI.

**Comment by jdemeyer** [comment]
I guess that this problem occurs when the PARI library is upgraded. So, in that case, you really want to reinstall `cypari2` too.

**Comment by vinklein** [comment]
To be more accurate, i have this problem when my cysignals install is older than the pari-gp install. 
Re-installing cypari2 with --upgrade doesn't solve the problem.

**Comment by jdemeyer** [comment]
> Re-installing cypari2 with --upgrade doesn't solve the problem.

Maybe not. I'm just saying that you would need to re-install ''both'' cysignals and cypari2 if you upgrade PARI.

**Comment by vinklein** [comment]
Ok.

**Comment by jdemeyer** [comment]
There is still the typo.

**Pull request merged**
