### PR TITLE
gen.pyx : Fix issue #44 List assignment

### PR DESCRIPTION
**Pull request by vinklein**
Fix ``__setitem__`` for ``t_LIST`` types

### CODE REVIEW

**Comment by videlec** [comment]
Nice! Wouldn't it be cleaner with
```
if typ(self.g) == t_LIST:
    listput(self.g, x.g, i+1)
else:
    if typ(self.g) == t_POL:
        i += 1
    set_gel(self.g, i+1, x.g)
```

**Comment by vinklein** [comment]
Cleaner but it would not work for `t_VEC` for example

**Comment by videlec** [comment]
why? It would be taken care of in the `else` branch.

**Comment by vinklein** [comment]
I totally agree and edited my message juste after posting it : ))

**Pull request merged**
