### PR TITLE
Clean up paridecl

### PR DESCRIPTION
**Pull request by jdemeyer**
- include `auto_paridecl.pxd` in `paridecl.pxd` such that user code no longer needs to worry which file to `cimport`.

- put the declarations for `pariinl.h` also in `paridecl.pxd` (there was no reason to put these in a different file and Cython semi-deprecated `.pxi` files so we should avoid them)

- declare some `enum` types as `cdef enum`

### CODE REVIEW

**Comment by jdemeyer** [comment]
@videlec What do you think of this pull request?

**Comment by videlec** [comment]
That you should remove declaration in `paridecl.pxd` that already appears in `auto_paridecl.pxd`.

**Comment by jdemeyer** [comment]
> That you should remove declarations in paridecl.pxd that already appears in auto_paridecl.pxd.

But why? If it's not broken, don't fix it! Especially if the fix involves a lot of manual work.

**Comment by videlec** [comment]
- to make it more maintainable
- make clearer what it really contains (`auto_paridecl.pxd` is kind of hidden)
- prevent us from having trouble about function signature in the future

**Comment by jdemeyer** [comment]
> to make it more maintainable

Your proposal makes it **less** maintainable. It requires extra effort every time that we want to update `paridecl.pxd`

> make clearer what it really contains (auto_paridecl.pxd is kind of hidden)

So what? The user only needs to care about `paridecl.pxd`. It doesn't matter how it is implemented.

> prevent us from having trouble about function signature in the future

Which trouble are we having?

**Comment by jdemeyer** [comment]
Independently of possible future improvements, would you agree with merging this pull request now? We can still continue the discussion about `paridecl.pxd` after that.

**Comment by videlec** [comment]
right

**Pull request merged**
